apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    tier: backend

spec:
  replicas: 3
  selector:
    matchLabels:
      app: v1
  
  template:
    
    metadata:
      labels:
        app: v1

    spec:
      containers:
      - name: nginx
        image: nginx:1.23.0


#
# 2045  k get deployments
# 2046  k get pods
#2047  cat deployments.yml 
# 2048  k set image deployment nginx nginx=nginx:1.23.4
# 2049  k rollout status deployment nginx
# 2050  k annotate depoyment nginx kubernetes.io/change-cause="Pick up patch version"
# 2051  k annotate deployment nginx kubernetes.io/change-cause="Pick up patch version"
# 2052  k scale deployment nginx --replicas=5
# 2053  k get deployments,pods
# 2054  k rollout history deployment nginx
# 2055  k rollout undo deployment nginx --to-revision=1
#
#
#
